logging:
    level:
        ROOT: error
        tech.jhipster: error
        com.park.utmstack: error

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASS}
        hikari:
            poolName: Hikari
            auto-commit: false
    jpa:
        database-platform: tech.jhipster.domain.util.FixedPostgreSQL10Dialect
    elasticsearch: # This configuration is for the elasticsearch health indicator, please do not remove
        rest:
            uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    liquibase:
        contexts: prod
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true

server:
    port: 8080
    shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
        min-response-size: 1024

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
        exposed-headers: 'Authorization,Link,X-Total-Count,X-UtmStack-alert,X-UtmStack-error,X-UtmStack-params'
        allow-credentials: false
        max-age: 1800
    security:
        authentication:
            jwt:
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from:
        base-url:

application:
    chart-builder: # Chart builder configuration
        ip-info-index-name: .utm-geoip
    incident-response:
        asset-verification-interval: 300

grpc:
    server:
        address: ${GRPC_AGENT_MANAGER_HOST}
        port: ${GRPC_AGENT_MANAGER_PORT}

management:
    info:
        build:
            enabled: true
