# Apache filter, version 3.0.0
# Compatible with Common Apache Log and Combined Apache Log. See: https://httpd.apache.org/docs/2.2/logs.html
#Filter Input requirements -> fileset: datatype
#                             access: plain text
# 1. Parsing the json from beats
# 2. Parsing the message field containing the apache log
pipeline:
  - dataTypes:
      - apache
    steps:
      - json:
          source: raw
      - rename:
          from:
            - log.url
          to: local.url
      - rename:
          from:
            - log.log.file.path
          to: local.file
      - rename:
          from:
            - log.host.ip
          to: local.ips
      - rename:
          from:
            - log.host.mac
          to: local.macs
      - rename:
          from:
            - log.host.hostname
          to: local.host
      - rename:
          from:
            - log.event.dataset
          to: action
      - rename:
          from:
            - log.agent.version
          to: log.agentVersion
      - rename:
          from:
            - log.host.os.kernel
          to: log.osVersion
      - rename:
          from:
            - log.host.os.type
          to: log.osType
      - rename:
          from:
            - log.host.architecture
          to: log.cpuArchitecture
      - cast:
          to: '[]string'
          fields:
            - local.ips
      - cast:
          to: '[]string'
          fields:
            - local.macs
      # Common apache log parsing
      - grok:
          patterns:
            - fieldName: local.ip
              pattern: '{{.ipv4}}|{{.ipv6}}'
            - fieldName: log.userIdent
              pattern: '{{.word}}|(-)'
            - fieldName: local.user
              pattern: '{{.word}}|(-)'
            - fieldName: deviceTime
              pattern: '\[{{.data}}\]'
            - fieldName: log.request
              pattern: '\"{{.data}}\"'
            - fieldName: log.statusCode
              pattern: '{{.integer}}'
            - fieldName: log.rest
              pattern: '{{.greedy}}'
          source: log.message
      # Parsing Common and Combined end of apache log
      # Common
      - grok:
          patterns:
            - fieldName: local.bytesReceived
              pattern: '{{.integer}}|(-)'
          source: log.rest
      # Combined
      - grok:
          patterns:
            - fieldName: local.bytesReceived
              pattern: '{{.integer}}|(-)'
            - fieldName: log.referer
              pattern: '\"{{.data}}\"'
            - fieldName: log.userAgent
              pattern: '\"(.*)\"'
          source: log.rest
      - trim:
          function: prefix
          substring: '['
          fields:
            - deviceTime
      - trim:
          function: suffix
          substring: ']'
          fields:
            - deviceTime
      - trim:
          function: prefix
          substring: '"'
          fields:
            - log.request
            - log.referer
            - log.userAgent
      - trim:
          function: suffix
          substring: '"'
          fields:
            - log.request
            - log.referer
            - log.userAgent
      # Extracting request parts
      - grok:
          patterns:
            - fieldName: log.method
              pattern: '{{.word}}'
            - fieldName: "local.path"
              pattern: '(.*)\s+'
            - fieldName: protocol
              pattern: '{{.greedy}}'
          source: log.request
      # Reformat and field conversions
      - cast:
          fields:
            - log.statusCode
            - local.bytesReceived
          to: int
      - reformat:
          fields:
            - deviceTime
          function: time
          fromFormat: '14/Feb/2022:15:40:53 -0500'
          toFormat: '2024-09-23T15:57:40.338364445Z'
      # Removing unused fields
      - delete:
          fields:
            - log.service
            - log.metadata
            - log.agent
            - log.host
            - log.event
            - log.ecs
            - log.log
            - log.rest
            - log.fileset
