name: Agent Build

on:
  release:
    types: [ 'released' ]
  push:
    branches: [ 'main', 'feature/**' ]
    paths:
      - 'agent/**'
  pull_request_review:
    types: [submitted]
    paths: 
      - 'agent/**'

jobs:
  check:
    name: Checking
    runs-on: ubuntu-latest
    outputs:
      env_tag: ${{ steps.set-env.outputs.env_tag }}
    steps:
      - name: Determine Build Environment
        id: set-env
        run: |
          if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') }}; then
            echo "DEV environment"
            echo "env_tag=dev" >> $GITHUB_OUTPUT
          elif ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'feature/') }}; then
            echo "QA environment"
            echo "env_tag=qa" >> $GITHUB_OUTPUT
          elif ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}; then
            echo "RC environment"
            echo "env_tag=rc" >> $GITHUB_OUTPUT
          elif ${{ github.event_name == 'release' }}; then
            echo "PRODUCTION environment"
            echo "env_tag=prod" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build
    needs: check
    if: needs.check.outputs.env_tag != ''
    runs-on: signing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Create build directory
        run: |
          mkdir build

      - name: Build and sign agent services
        id: set-env
        run: |
          go version
        
          cd ${{ github.workspace }}/agent/agent/config; (Get-Content const.go) | Foreach-Object { $_ -replace 'const REPLACE_KEY string = ""', 'const REPLACE_KEY string = "${{ secrets.AGENT_SECRET_PREFIX }}"' } | Set-Content const.go
          
          $env:GOOS = "linux"
          $env:GOARCH = "amd64"
          cd ${{ github.workspace }}/agent/agent; go build -o ${{ github.workspace }}/build/utmstack_agent_service -v .
          cd ${{ github.workspace }}/agent/installer; go build -o ${{ github.workspace }}/build/utmstack_agent_installer -v .
          
          $env:GOOS = "windows"
          cd ${{ github.workspace }}/agent/agent; go build -o ${{ github.workspace }}/build/utmstack_agent_service.exe -v .
          signtool sign /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 /f "${{ vars.SIGN_CERT }}" /csp "eToken Base Cryptographic Provider" /k "[{{${{ secrets.SIGN_KEY }}}}]=${{ secrets.SIGN_CONTAINER }}" "utmstack_agent_service.exe"
          cd ${{ github.workspace }}/agent/installer; go build -o ${{ github.workspace }}/build/utmstack_agent_installer.exe -v .
          signtool sign /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 /f "${{ vars.SIGN_CERT }}" /csp "eToken Base Cryptographic Provider" /k "[{{${{ secrets.SIGN_KEY }}}}]=${{ secrets.SIGN_CONTAINER }}" "utmstack_agent_installer.exe"

          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.12.1/python-3.12.1-amd64.exe" -OutFile "python-installer.exe"
          Start-Process -FilePath "python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
          Remove-Item -Path "python-installer.exe"
          python -m pip install --upgrade pip
          pip install requests pyyaml

          $env:PUBLISHER_KEY = '${{ secrets.["PUBLISHER_KEY_${{ needs.check.outputs.env_tag }}".ToUpper()] }}'
          $env:CM_SERVER = '${{ secrets.["CM_SERVER_${{ needs.check.outputs.env_tag }}".ToUpper()] }}'
          
          cd ${{ github.workspace }}/.github/scripts; & 'C:\Program Files\Python312\python.exe' 'services-deploy.py' ${{ needs.check.outputs.env_tag }} 'agent'
          cd ${{ github.workspace }}; Remove-Item -Path "./*" -Recurse -Force
      